### ISSUE TITLE
新增題目時卡住

### ISSUE THREAD

**Issue by W-X-Dai** [HimitZH/HOJ#23]
您好，我在新增題目時有時網頁會卡住，並且回傳請求超時的訊息

**Comment by HimitZH** [comment]
我想你指的是远程题目吧 你都不说你咋操作的 问的是某个OJ的题目获取不了吧 先自己考虑下是不是自己服务器都访问不了这个OJ

**Comment by W-X-Dai** [comment]
不是啊大佬，我是手動新增題目的時候卡住。題目敘述還有測資都弄好之後點擊「儲存」，網頁沒反應知道幾分鐘後告訴我請求超時

**Comment by W-X-Dai** [comment]
這是點擊保存後回傳的錯誤訊息：
chunk-vendors.9cdd596d.js:87 TypeError: Cannot read properties of undefined (reading 'contentType')
    at problem.spjLanguage (app.e803a421.js:1:476921)
    at ni.run (chunk-vendors.9cdd596d.js:87:31514)
    at Qn (chunk-vendors.9cdd596d.js:87:29624)
    at Array.<anonymous> (chunk-vendors.9cdd596d.js:87:12761)
    at ct (chunk-vendors.9cdd596d.js:87:12156)

**Comment by HimitZH** [comment]
你自己是否改動過前端頁面的代碼，你給的錯誤訊息是前端的抱錯，如果沒改動過，建議先更新下整個網站，包括前端頁面和後端服務，只需要用`docker-compose pull` 和 `docker-compose up -d`這兩行命令在服務器上執行即可

**Comment by HimitZH** [comment]
注意：上面說的兩行命令需要在有**docker-compose.yml**的同級目錄下執行

**Comment by W-X-Dai** [comment]
已經解決了，謝謝
