### ISSUE TITLE
5050 端口没有跑起来

### ISSUE THREAD

**Issue by yuen619** [HimitZH/HOJ#69]
Docker Version: 26.1.4

Logs:

nacos is ok 
 ./Sandbox-amd64 --silent=true --file-timeout=5m 
2024/08/12 21:41:53 prefork environment failed  container: failed to start container fork/exec /proc/self/exe: invalid argument

        ,--,               ,----..
      ,--.'|  ,----..     /   /   \      ,---,        ,---,.
   ,--,  | : /   /   \   /   .     :   .'  .' `\    ,'  .' |
,---.'|  : '|   :     : .   /   ;.  \,---.'     \ ,---.'   |
|   | : _' |.   |  ;. /.   ;   /  ` ;|   |  .`\  ||   |   .'
:   : |.'  |.   ; /--` ;   |  ; \ ; |:   : |  '  |:   :  |-,
|   ' '  ; :;   | ;    |   :  | ; | '|   ' '  ;  ::   |  ;/|
'   |  .'. ||   : |    .   |  ' ' ' :'   | ;  .  ||   :   .'
|   | :  | '.   | '___ '   ;  \; /  ||   | :  |  '|   |  |-,
'   : |  : ;'   ; : .'| \   \  ',  / '   : | /  ; '   :  ;/|
|   | '  ,/ '   | '/  :  ;   :    /  |   | '` ,/  |   |    \
;   : ;--'  |   :    /    \   \ .'   ;   :  .'    |   :   .'
|   ,/       \   \ .'      `---`     |   ,.'      |   | ,'
'---'         `---`                  '---'        `----'
            Hcode Online Judge(HOJ) - JudgeServer
                    @Author Himit_ZH
                    @Last Update 20240330
          ->Github<- https://www.github.com/HimitZH/HOJ
          ->Gitee<-  https://gitee.com/himitzh0730/hoj
2024-08-12 21:43:05 [http-nio-8088-exec-2] ERROR hoj - [Judge] [System Runtime Error] Submit Id:[1] Problem Id:[1000], Error:[{}] 
java.util.concurrent.ExecutionException: SystemError(message=Call SandBox Error., stdout=null, stderr=I/O error on POST request for "http://localhost:5050/run": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused))
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at top.hcode.hoj.judge.JudgeRun.SubmitBatchTask2ThreadPool(JudgeRun.java:435)
	at top.hcode.hoj.judge.JudgeRun.defaultJudgeAllCase(JudgeRun.java:175)
	at top.hcode.hoj.judge.JudgeRun.judgeAllCase(JudgeRun.java:113)
	at top.hcode.hoj.judge.JudgeStrategy.judge(JudgeStrategy.java:93)
	at top.hcode.hoj.judge.JudgeContext.Judge(JudgeContext.java:50)
	at top.hcode.hoj.service.impl.JudgeServiceImpl.judge(JudgeServiceImpl.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:499)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at top.hcode.hoj.service.impl.JudgeServiceImpl$$EnhancerBySpringCGLIB$$60dcef0b.judge(<generated>)
	at top.hcode.hoj.controller.JudgeController.submitProblemJudge(JudgeController.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:499)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at top.hcode.hoj.controller.JudgeController$$EnhancerBySpringCGLIB$$b4f2b3b3.submitProblemJudge(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: top.hcode.hoj.common.exception.SystemError: Call SandBox Error.
	at top.hcode.hoj.judge.SandboxRun.run(SandboxRun.java:161)
	at top.hcode.hoj.judge.SandboxRun.testCase(SandboxRun.java:385)
	at top.hcode.hoj.judge.task.DefaultJudge.judgeCase(DefaultJudge.java:30)
	at top.hcode.hoj.judge.AbstractJudge.judge(AbstractJudge.java:41)
	at top.hcode.hoj.judge.JudgeRun.lambda$defaultJudgeAllCase$0(JudgeRun.java:164)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 common frames omitted

判题异常，Oops, something has gone wrong with the judgeServer. Please report this to administrator.

**Comment by HimitZH** [comment]
看文档说明：[docs.hdoi.cn](https://docs.hdoi.cn/deploy/faq/#%E4%B8%80%E3%80%81%E9%83%A8%E7%BD%B2%E5%9C%A8centos7%E7%B3%BB%E7%BB%9F%E4%B8%AD%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E8%AF%84%E6%B5%8B-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)
